# Gitleaks Configuration - Comprehensive Security-Focused Allowlist
# This configuration provides comprehensive patterns for legitimate examples, test data, and documentation
# while maintaining security by being specific about allowed patterns

# Use default Gitleaks rules as baseline
[extend]
useDefault = true

# Single allowlist section with combined paths and regexes
[allowlist]
paths = [
  '''README\.md''',
  '''CLAUDE\.md''',
  '''CHANGELOG\.md''',
  '''CONTRIBUTING\.md''',
  '''CODE_OF_CONDUCT\.md''',
  '''SECURITY\.md''',
  '''docs/.*\.md''',
  '''apps/docs/.*\.md''',
  '''apps/api/docs/.*\.md''',
  '''.*\.example''',
  '''.*\.template''',
  '''.*\.sample''',
  '''build/.*''',
  '''dist/.*''',
  '''coverage/.*''',
  '''.*/__tests__/.*''',
  '''.*/__mocks__/.*''',
  '''test/.*''',
  '''tests/.*''',
  '''fixtures/.*''',
  '''.*\.test\..*''',
  '''.*\.spec\..*''',
  '''.*\.integration\.test\..*''',
  '''docker-compose\.test\.yml''',
  '''.*\.test\.yml''',
  '''scripts/test-.*\.ps1''',
  '''apps/api/src/config/test-config\.ts''',
  '''apps/api/vitest\.unit\.config\.ts''',
  '''apps/api/vitest\.integration\.config\.ts''',
  '''\.env\.example''',
  '''\.env\..*\.example''',
  '''example\.env''',
  '''\.env\.template'''
]
regexes = [
  # Explicit placeholders
  '''<REDACTED[^>]*>''',
  '''<your[^>]*>''',
  '''<replace[^>]*>''',
  '''YOUR_[A-Z_]*_HERE''',
  '''REPLACE_WITH_[A-Z_]*''',
  '''your-[a-z-]*-here''',
  '''your-[a-z-]*-secret''',
  '''your-[a-z-]*-token''',
  '''your-[a-z-]*-key''',
  '''placeholder-[a-z-]*''',
  '''example-[a-z-]*''',
  '''dummy-[a-z-]*''',
  '''fake-[a-z-]*''',
  
  # Test patterns
  '''test-.*-secret''',
  '''test-.*-token''',
  '''test-.*-key''',
  '''FAKE_[A-Z_]+''',
  '''TEST_[A-Z_]+''',
  '''EXAMPLE_[A-Z_]+''',
  
  # Specific fake test patterns for FlakeGuard
  '''FAKE_PRIVATE_KEY_FOR_TESTS_ONLY''',
  '''FAKE_API_KEY_FOR_TESTS_ONLY_123''',
  '''FAKE_TOKEN_FOR_TESTS_ONLY''',
  
  # Fake private key patterns
  '''-----BEGIN FAKE PRIVATE KEY FOR TESTS ONLY-----.*-----END FAKE PRIVATE KEY FOR TESTS ONLY-----''',
  '''THIS_IS_A_FAKE_KEY_FOR_TESTING_PURPOSES_ONLY''',
  '''DO_NOT_USE_IN_PRODUCTION_ENVIRONMENTS''',
  
  # API documentation examples
  '''fg_EXAMPLE_[A-Za-z0-9_]+''',
  '''Bearer\s+fg_EXAMPLE_[A-Za-z0-9_]+''',
  
  # Test Slack tokens (clearly marked as test)
  '''xoxb-test-[a-zA-Z0-9-]*''',
  '''xapp-test-[a-zA-Z0-9-]*''',
  
  # Development database URLs
  '''postgresql://postgres:postgres@.*''',
  '''redis://redis:6379.*''',
  '''redis://localhost:6379.*''',
  
  # GitHub Actions syntax
  '''\$\{\{\s*secrets\.[A-Za-z_][A-Za-z0-9_]*\s*\}\}''',
  '''\$\{\{\s*env\.[A-Za-z_][A-Za-z0-9_]*\s*\}\}''',
  
  # Environment variable assignments with safe development values
  '''JWT_SECRET\s*=\s*['"]?your-[a-z-]+-change-this['"]?''',
  '''API_KEY\s*=\s*['"]?your-[a-z-]+-change-this['"]?''',
  '''GITHUB_PRIVATE_KEY\s*=\s*['"]?FAKE_PRIVATE_KEY_FOR_TESTS['"]?''',
  '''SLACK_BOT_TOKEN\s*=\s*['"]?xoxb-test-[a-zA-Z0-9-]+['"]?''',
  
  # Common JWT example token from jwt.io (John Doe example)
  '''eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0\.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c''',
  
  # Slack webhook examples
  '''https://hooks\.slack\.com/services/T[A-Z0-9]{8,}/B[A-Z0-9]{8,}/EXAMPLE''',
  '''https://hooks\.slack\.com/services/.*/EXAMPLE''',
  
  # Authorization headers in documentation
  '''Authorization:\s*(Bearer|token)\s+[^'"\s]*''',
  '''curl.*-H.*Authorization.*''',
  
  # Test and development patterns
  '''.*(test|example|placeholder|mock|fake|dummy|sample)[_-]+(secret|token|key|password).*''',
  '''.*(secret|token|key|password)[_-]+(test|example|placeholder|mock|fake|dummy|sample).*''',
  '''.*localhost[:/].*''',
  '''.*127\.0\.0\.1[:/].*''',
  
  # Obvious change-this patterns
  '''[a-zA-Z0-9]*-change-this[a-zA-Z0-9-]*''',
  '''[a-zA-Z0-9]*-replace[a-zA-Z0-9-]*''',
  '''[a-zA-Z0-9]*-placeholder[a-zA-Z0-9-]*''',
  
  # Minimum character requirements mentioned in examples
  '''[a-zA-Z-]*secret[a-zA-Z-]*minimum[a-zA-Z0-9-]*characters[a-zA-Z0-9-]*''',
  
  # CI environment variables with test values
  '''test-jwt-secret-minimum-32-characters-long-for-testing-only''',
  '''test-api-key-minimum-16-chars-for-testing''',
  
  # Base64 encoded test data
  '''base64-encoded-private-key-for-octokit-helpers''',
  '''base64-encoded-.*-for-.*-helpers''',
  
  # Common webhook secrets in development
  '''your-webhook-secret''',
  '''your-github-client-secret''',
  '''your-slack-signing-secret''',
  
  # GitHub App configuration examples
  '''your-github-client-id''',
  '''optional-single-tenant-installation-id''',
  
  # Slack configuration examples
  '''xoxb-test-placeholder-token''',
  '''xapp-test-placeholder-token''',
  
  # File path examples
  '''\./github-app-private-key\.pem''',
  
  # Numeric IDs (not secrets)
  '''GITHUB_APP_ID\s*=\s*[0-9]+'''
]