# Gitleaks Configuration for FlakeGuard
# This configuration extends the default rules and adds custom allowlists

[extend]
useDefault = true

# Custom allowlists for false positives
[[allowlists]]
description = "Allow documentation example files"
paths = [
  '''apps/docs/docs/.*\.md''',
  '''docs/.*\.md''',
  '''.*\.example''',
  '''README\.md'''
]

[[allowlists]]
description = "Allow safe placeholder tokens"
regexes = [
  '''Authorization:\s*<REDACTED_TOKEN>''',
  '''Authorization:\s*Bearer\s*<REDACTED_TOKEN>''',
  '''Authorization:\s*token\s*<REDACTED_TOKEN>''',
  '''Authorization:\s*Bearer\s*flakeguard_[a-zA-Z0-9]+''',
  '''FAKE_PRIVATE_KEY_FOR_TESTS''',
  '''-----BEGIN RSA PRIVATE KEY-----\s*FAKE_PRIVATE_KEY_FOR_TESTS''',
  '''<your_.*>''',
  '''<base64_encoded_.*>''',
  '''xoxb-test-.*''',
  '''xoxb-1234567890-.*''',
  '''xapp-test-.*''',
  '''test-webhook-secret''',
  '''your-secret-here''',
  '''placeholder-.*''',
  '''example-.*''',
  '''dummy-.*''',
  '''fake-.*''',
  '''https://hooks\.slack\.com/services/T00000000/B00000000/.*'''
]

[[allowlists]]
description = "Allow test fixtures and mock data"
paths = [
  '''.*/__tests__/.*''',
  '''.*\.test\..*''',
  '''.*\.spec\..*''',
  '''test/.*''',
  '''tests/.*''',
  '''docker-compose\.test\.yml'''
]

[[allowlists]]
description = "Allow environment variable examples"
files = [
  '''\.env\.example''',
  '''\.env\..*\.example''',
  '''example\.env'''
]

[[allowlists]]
description = "Allow GitHub Actions placeholders"
regexes = [
  '''\$\{\{\s*secrets\..*\s*\}\}''',
  '''\$\{\{\s*github\.token\s*\}\}'''
]

[[allowlists]]
description = "Allow development database connection strings"
regexes = [
  '''postgresql://postgres:postgres@.*''',
  '''postgresql://user:password@.*''',
  '''postgresql://username:password@.*''',
  '''postgres://postgres:postgres@.*''',
  '''postgres://user:password@.*''',
  '''postgres://username:password@.*''',
  '''DATABASE_URL=postgresql://.*''',
  '''redis://redis:6379.*''',
  '''redis://localhost:6379.*''',
  '''@postgres:5432''',
  '''@localhost:5432''',
  '''@redis:6379''',
  '''@localhost:6379'''
]

[[allowlists]]
description = "Allow Docker Compose database configurations"
paths = [
  '''docker-compose.*\.yml''',
  '''docker-compose.*\.yaml'''
]
regexes = [
  '''postgresql://.*''',
  '''redis://.*'''
]