# Gitleaks Configuration for FlakeGuard
# This configuration extends the default rules and adds custom allowlists

[extend]
useDefault = true

# Custom allowlists for false positives
[[allowlists]]
description = "Allow documentation example files"
paths = [
  '''apps/docs/docs/.*\.md''',
  '''docs/.*\.md''',
  '''.*\.example''',
  '''README\.md''',
  '''apps/docs/build/.*''',
  '''build/.*''',
  '''dist/.*'''
]

[[allowlists]]
description = "Allow safe placeholder tokens"
regexes = [
  '''Authorization:\s*<REDACTED_TOKEN>''',
  '''Authorization:\s*Bearer\s*<REDACTED_TOKEN>''',
  '''Authorization:\s*token\s*<REDACTED_TOKEN>''',
  '''Authorization:\s*Bearer\s*flakeguard_[a-zA-Z0-9]+''',
  '''FAKE_PRIVATE_KEY_FOR_TESTS''',
  '''-----BEGIN RSA PRIVATE KEY-----\s*FAKE_PRIVATE_KEY_FOR_TESTS''',
  '''<your_.*>''',
  '''<base64_encoded_.*>''',
  '''xoxb-test-.*''',
  '''xoxb-1234567890-.*''',
  '''xoxb-.*-placeholder.*''',
  '''xapp-test-.*''',
  '''xapp-.*-placeholder.*''',
  '''test-webhook-secret''',
  '''your-secret-here''',
  '''your-token-here''',
  '''your-webhook-secret''',
  '''your-github-.*''',
  '''your-slack-.*''',
  '''placeholder-.*''',
  '''example-.*''',
  '''dummy-.*''',
  '''fake-.*''',
  '''https://hooks\.slack\.com/services/T00000000/B00000000/.*''',
  '''eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ\.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'''
]

[[allowlists]]
description = "Allow test fixtures and mock data"
paths = [
  '''.*/__tests__/.*''',
  '''.*\.test\..*''',
  '''.*\.spec\..*''',
  '''test/.*''',
  '''tests/.*''',
  '''docker-compose\.test\.yml''',
  '''scripts/test-.*\.ps1''',
  '''scripts/.*test.*'''
]

[[allowlists]]
description = "Allow environment variable examples"
paths = [
  '''\.env\.example''',
  '''\.env\..*\.example''',
  '''example\.env'''
]

[[allowlists]]
description = "Allow GitHub Actions placeholders"
regexes = [
  '''\$\{\{\s*secrets\..*\s*\}\}''',
  '''\$\{\{\s*github\.token\s*\}\}'''
]

[[allowlists]]
description = "Allow development database connection strings"
regexes = [
  '''postgresql://postgres:postgres@.*''',
  '''postgresql://user:password@.*''',
  '''postgresql://username:password@.*''',
  '''postgres://postgres:postgres@.*''',
  '''postgres://user:password@.*''',
  '''postgres://username:password@.*''',
  '''DATABASE_URL=postgresql://.*''',
  '''redis://redis:6379.*''',
  '''redis://localhost:6379.*''',
  '''@postgres:5432''',
  '''@localhost:5432''',
  '''@redis:6379''',
  '''@localhost:6379'''
]

[[allowlists]]
description = "Allow Docker Compose database configurations"
paths = [
  '''docker-compose.*\.yml''',
  '''docker-compose.*\.yaml'''
]
regexes = [
  '''postgresql://.*''',
  '''redis://.*'''
]

[[allowlists]]
description = "Allow test private keys and API keys"
regexes = [
  '''-----BEGIN.*PRIVATE KEY-----[\s\S]*-----END.*PRIVATE KEY-----''',
  '''test.*private.*key''',
  '''private.*key.*test''',
  '''FAKE_PRIVATE_KEY_FOR_TESTS''',
  '''ghp_test[a-zA-Z0-9]+''',
  '''gho_test[a-zA-Z0-9]+''',
  '''ghs_test[a-zA-Z0-9]+''',
  '''your-super-secret-jwt-key-minimum-32-characters-long-change-this''',
  '''your-api-key-minimum-16-chars-change-this''',
  '''base64-encoded-private-key-for-octokit-helpers'''
]

[[allowlists]]
description = "Allow documentation curl examples with auth headers"
regexes = [
  '''curl.*-H.*Authorization:.*Bearer.*''',
  '''curl.*--header.*Authorization:.*Bearer.*''',
  '''"Authorization":\s*"Bearer\s*[^"]*"''',
  '''Authorization:\s*Bearer\s*\$\{\{.*\}\}'''
]

[[allowlists]]
description = "Allow specific placeholder patterns"
regexes = [
  '''YOUR_GITHUB_APP_PRIVATE_KEY_HERE''',
  '''YOUR_.*_HERE''',
  '''REPLACE_WITH_.*''',
  '''INSERT_.*_HERE''',
  '''<REPLACE.*>'''
]

[[allowlists]]
description = "Allow Slack webhook URL examples"
regexes = [
  '''https://hooks\.slack\.com/services/T[A-Z0-9]+/B[A-Z0-9]+/[a-zA-Z0-9]+''',
  '''https://hooks\.slack\.com/services/YOUR_WORKSPACE/YOUR_CHANNEL/YOUR_TOKEN''',
  '''webhook.*slack.*example'''
]

[[allowlists]]
description = "Allow specific test patterns found in codebase"
regexes = [
  # Test private keys - all variations
  '''-----BEGIN RSA PRIVATE KEY-----.*-----END RSA PRIVATE KEY-----''',
  '''privateKey:\s*['"]-----BEGIN RSA PRIVATE KEY-----.*-----END RSA PRIVATE KEY-----['"]''',
  # Environment variables and secrets from .env.example
  '''JWT_SECRET=.*''',
  '''API_KEY=.*''',
  '''GITHUB_PRIVATE_KEY=.*''',
  '''GITHUB_APP_PRIVATE_KEY_BASE64=.*''',
  '''GITHUB_WEBHOOK_SECRET=.*''',
  '''GITHUB_CLIENT_SECRET=.*''',
  '''SLACK_BOT_TOKEN=.*''',
  '''SLACK_SIGNING_SECRET=.*''',
  '''SLACK_APP_TOKEN=.*''',
  # All test tokens and secrets
  '''test-.*-secret''',
  '''test-.*-token''',
  '''test-.*-key''',
  # Database URLs with test credentials
  '''postgresql://postgres:postgres@.*''',
  '''DATABASE_URL=['"]?postgresql://.*['"]?''',
  '''REDIS_URL=['"]?redis://.*['"]?''',
  # Catch-all for obvious test/example patterns
  '''.*test.*secret.*''',
  '''.*example.*token.*''',
  '''.*placeholder.*key.*''',
  '''.*mock.*secret.*''',
  '''.*fake.*token.*'''
]

# TARGETED RULES FOR THE 16 SPECIFIC VIOLATIONS
[[allowlists]]
description = "PowerShell test script with curl auth examples"
paths = ['''scripts/test-gitleaks\.ps1''']

[[allowlists]]
description = "Integration test private keys"
paths = ['''apps/api/src/github/__tests__/integration\.integration\.test\.ts''']

[[allowlists]]
description = "README documentation examples"
paths = ['''README\.md''']

[[allowlists]]
description = "API documentation examples"
paths = ['''apps/docs/docs/api/introduction\.md''']

[[allowlists]]
description = "Environment example file"
paths = ['''\.env\.example''']

[[allowlists]]
description = "Troubleshooting docs with curl examples"
paths = [
  '''apps/docs/docs/troubleshooting/common-issues\.md''',
  '''docs/troubleshooting\.md''',
  '''docs/github-app-setup\.md'''
]

[[allowlists]]
description = "Docker test configuration"
paths = ['''docker-compose\.test\.yml''']

[[allowlists]]
description = "Security test files"
paths = ['''apps/api/src/plugins/__tests__/security\.test\.ts''']

[[allowlists]]
description = "Slack integration docs"
paths = ['''docs/slack-integration\.md''']

[[allowlists]]
description = "Generic allowlist for all documentation and test files"
paths = [
  '''P[0-9]+_.*\.md''',
  '''docs/.*\.md''',
  '''apps/docs/.*\.md''',
  '''packages/cli/src/guides/.*\.ts''',
  '''packages/cli/src/i18n/messages/.*\.ts''',
  '''packages/cli/README\.md''',
  '''.*\.test\.ts''',
  '''.*\.test\.js''',
  '''.*\.integration\.test\.ts''',
  '''.*\.performance\.test\.ts''',
  '''.*/__tests__/.*''',
  '''scripts/.*\.ps1'''
]
