# TruffleHog Configuration for FlakeGuard
# Defines custom detectors and exclusion patterns

# Exclude paths from scanning
exclude:
  paths:
    - '\.git/'
    - 'node_modules/'
    - 'dist/'
    - 'build/'
    - 'coverage/'
    - '\.next/'
    - '\.turbo/'
    - 'tmp/'
    - 'temp/'
    - '.*\.min\.js$'
    - '.*\.min\.css$'
    - '.*\.map$'
    - '.*\.lock$'
    - 'pnpm-lock\.yaml$'
    - 'package-lock\.json$'
    - 'yarn\.lock$'

  # Exclude specific file patterns
  files:
    - '\.env\.example$'
    - '\.env\..*\.example$'
    - 'example\.env$'
    - '.*\.example$'
    - '.*\.sample$'
    - '.*\.template$'

# Allow patterns for known false positives
allow:
  # Test files and fixtures
  - path: '.*/__tests__/.*'
  - path: '.*\.test\..*'
  - path: '.*\.spec\..*'
  - path: 'test/.*'
  - path: 'tests/.*'
  - path: '.*/__mocks__/.*'
  - path: 'fixtures/.*'

  # Documentation
  - path: 'docs/.*\.md$'
  - path: 'apps/docs/.*\.md$'
  - path: 'README\.md$'
  - path: '.*\.md$'
    content: '<your_.*>'
  - path: '.*\.md$'
    content: '<base64_encoded_.*>'
  - path: '.*\.md$'
    content: 'placeholder'
  - path: '.*\.md$'
    content: 'example'

  # GitHub Actions placeholders
  - content: '\$\{\{.*secrets\..*\}\}'
  - content: '\$\{\{.*github\.token.*\}\}'
  - content: '\$\{\{.*env\..*\}\}'

  # Common test/example patterns
  - content: 'xoxb-test-.*'
  - content: 'xapp-test-.*'
  - content: 'test-webhook-secret'
  - content: 'your-secret-here'
  - content: 'placeholder-.*'
  - content: 'example-.*'
  - content: 'dummy-.*'
  - content: 'fake-.*'
  - content: 'mock-.*'
  - content: 'sample-.*'
  - content: 'demo-.*'
  - content: 'FAKE_PRIVATE_KEY_FOR_TESTS'
  - content: '<REDACTED.*>'
  - content: 'Bearer <token>'
  - content: 'Authorization: Bearer test'

# Detector-specific configurations
detectors:
  # Reduce noise from high-entropy detectors
  - name: HighEntropyBase64
    keywords:
      - 'PRIVATE'
      - 'SECRET'
      - 'TOKEN'
      - 'KEY'
      - 'PASSWORD'
      - 'PASS'
    entropy_threshold: 5.0

  - name: HighEntropyHex
    keywords:
      - 'PRIVATE'
      - 'SECRET'
      - 'TOKEN'
      - 'KEY'
      - 'PASSWORD'
      - 'PASS'
    entropy_threshold: 4.5

# Verification settings
verification:
  # Skip verification for detectors that make external calls
  skip:
    - AWS
    - GitHub
    - Slack
    - NPM

# Output settings
output:
  format: json
  verbose: false