# Prometheus configuration for FlakeGuard
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'flakeguard'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rule files
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # FlakeGuard API
  - job_name: 'flakeguard-api'
    static_configs:
      - targets: ['api:3000']  # Use Docker service name
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # FlakeGuard Worker
  - job_name: 'flakeguard-worker'
    static_configs:
      - targets: ['worker:3001']  # Assuming worker exposes metrics on 3001
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics

  # Custom application metrics discovery
  - job_name: 'flakeguard-discovery'
    dns_sd_configs:
      - names:
        - 'tasks.flakeguard-api'
        - 'tasks.flakeguard-worker'
        type: 'A'
        port: 3000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'localhost:9090'

# Remote write configuration (for external TSDB)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: 'username'
#       password: 'password'

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB
    path: /prometheus
    wal-compression: true

# Web configuration
web:
  console:
    libraries: /etc/prometheus/console_libraries
    templates: /etc/prometheus/consoles
  enable-lifecycle: true
  enable-admin-api: false
  max-connections: 512
  read-timeout: 30s