name: OSV Security Scanner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run nightly at 2 AM UTC for continuous vulnerability monitoring
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  osv-scan:
    name: OSV Vulnerability Scanning
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.2.1
    permissions:
      actions: read
      contents: read
      security-events: write
    with:
      scan-args: |
        --recursive ./
        --severity=HIGH,CRITICAL
      fail-on-vuln: true
